import fs from 'node:fs';
import path from 'node:path';
import { createHash } from 'node:crypto';
import { numberVhhForLeakage, alignGlobalAffine, evaluateFrozenVhhThreshold } from '/workspace/scratch/746bb3989941/ConfoVHH/scripts/hard-decoy/v3-vhh-sequence-pregraph.mjs';
import { Annotator } from '/workspace/scratch/746bb3989941/ConfoVHH/node_modules/immunum/immunum.js';
const root='/workspace/scratch/746bb3989941/ConfoVHH';
const hash=s=>createHash('sha256').update(s).digest('hex');
const read=(p)=>fs.readFileSync(path.join(root,p));
const jsonl=p=>read(p).toString().trim().split('\n').map(JSON.parse);
const candidateFile='validation/hard-decoy-holdout-v3/domain-remainder-2026-09-04/entries.jsonl';
const developmentFile='validation/hard-decoy-holdout-v3/development-metadata-snapshot-2026-08-29/entities.jsonl';
const profileFile='validation/hard-decoy-holdout-v3/vhh-sequence-pregraph-2026-08-29/development-vhh-profiles.jsonl';
const contractFile='validation/hard-decoy-holdout-v3/vhh-sequence-contract-2026-08-29.json';
const files=[candidateFile,developmentFile,profileFile,contractFile,'scripts/hard-decoy/v3-vhh-sequence-pregraph.mjs','package-lock.json','node_modules/immunum/package.json','node_modules/immunum/immunum.js','node_modules/immunum/immunum_bg.wasm'];
const entries=jsonl(candidateFile),devEntities=jsonl(developmentFile),profiles=jsonl(profileFile);
const chosen=[['9W3K','5'],['9W3L','2']].map(([pdbId,entityId])=>{const entry=entries.find(x=>x.pdbId===pdbId);return {...entry.polymerEntities.find(x=>x.entityId===entityId),pdbId};});
function region(position){ const n=parseInt(position,10);if(n<=26)return 'FR1-IMGT';if(n<=38)return 'CDR1-IMGT';if(n<=55)return 'FR2-IMGT';if(n<=65)return 'CDR2-IMGT';if(n<=104)return 'FR3-IMGT';if(n<=117)return 'CDR3-IMGT';return 'FR4-IMGT';}
function profile(entity){
 if(hash(entity.sequence)!==entity.sequenceSha256)throw Error('Source sequence digest mismatch '+entity.rcsbId);
 const numbered=numberVhhForLeakage(entity.sequence);if(numbered.numberingStatus!=='NUMBERED')throw Error('Failed to number '+entity.rcsbId);
 const a=new Annotator(['H'],'imgt',0.5);const raw=a.number(entity.sequence);const seg=a.segment(entity.sequence);a.free();
 const numbering=[...raw.numbering.entries()].map(([position,residue],i)=>({imgtPosition:position,residue,fullSequencePosition1Based:raw.query_start+i+1,variableDomainPosition1Based:i+1,region:region(position)}));
 const variableDomainSequence=entity.sequence.slice(numbered.queryStart,numbered.queryEnd+1);
 return {rcsbId:entity.rcsbId,pdbId:entity.pdbId,entityId:entity.entityId,description:entity.description,authAsymIds:entity.authAsymIds,labelAsymIds:entity.labelAsymIds,fullSequence:entity.sequence,fullSequenceLength:entity.sequence.length,fullSequenceSha256:hash(entity.sequence),numbering:numbered,variableDomainSequence,variableDomainLength:variableDomainSequence.length,variableDomainSha256:hash(variableDomainSequence),variableDomainFullSequenceSpan1BasedInclusive:[numbered.queryStart+1,numbered.queryEnd+1],prefixOutsideNumberedDomain:entity.sequence.slice(0,numbered.queryStart),suffixOutsideNumberedDomain:entity.sequence.slice(numbered.queryEnd+1),segments:Object.fromEntries(['fr1','cdr1','fr2','cdr2','fr3','cdr3','fr4'].map(k=>[k,seg[k]])),numberedResidues:numbering};
}
const candidates=chosen.map(profile),development=profiles.map(p=>profile(devEntities.find(e=>e.rcsbId===p.pdbId+'_'+p.entityId)));
function comparison(left,right){
 const full=alignGlobalAffine(left.fullSequence,right.fullSequence),domain=alignGlobalAffine(left.variableDomainSequence,right.variableDomainSequence),framework=alignGlobalAffine(left.numbering.frameworkSequence,right.numbering.frameworkSequence),cdr3=alignGlobalAffine(left.numbering.cdr3Sequence,right.numbering.cdr3Sequence);
 const rightByPos=new Map(right.numberedResidues.map(r=>[r.imgtPosition,r]));const leftByPos=new Map(left.numberedResidues.map(r=>[r.imgtPosition,r]));
 const positionOrder=[...new Set([...left.numberedResidues,...right.numberedResidues].map(r=>r.imgtPosition))].sort((a,b)=>parseInt(a,10)-parseInt(b,10)||a.localeCompare(b));
 const numberedDifferences=positionOrder.filter(p=>leftByPos.get(p)?.residue!==rightByPos.get(p)?.residue).map(p=>({imgtPosition:p,left:leftByPos.get(p)??null,right:rightByPos.get(p)??null}));
 return {leftRcsbId:left.rcsbId,rightRcsbId:right.rcsbId,fullSequenceExactMatch:left.fullSequence===right.fullSequence,numberedVariableDomainExactMatch:left.variableDomainSequence===right.variableDomainSequence,fullSequenceGlobalAlignment:full,numberedVariableDomainGlobalAlignment:domain,frameworkGlobalAlignment:framework,cdr3GlobalAlignment:cdr3,frozenSequenceCriterion:evaluateFrozenVhhThreshold({framework,cdr3,cdr3LengthA:left.numbering.cdr3Length,cdr3LengthB:right.numbering.cdr3Length}),cdr1ExactMatch:left.segments.cdr1===right.segments.cdr1,cdr2ExactMatch:left.segments.cdr2===right.segments.cdr2,cdr3ExactMatch:left.segments.cdr3===right.segments.cdr3,imgtPositionMappedDifferences:numberedDifferences};
}
for (const p of profiles) { const reproduced=development.find(d=>d.rcsbId===p.pdbId+'_'+p.entityId); for (const k of ['frameworkSequence','cdr3Sequence','queryStart','queryEnd','numberingStatus']) { if (reproduced.numbering[k]!==p[k]) throw Error('Frozen profile reproduction failed '+p.profileId+' '+k); } }
const comparisons=development.map(d=>comparison(candidates[0],d)).sort((a,b)=>b.numberedVariableDomainGlobalAlignment.identity-a.numberedVariableDomainGlobalAlignment.identity);
const output={schemaVersion:1,status:'LOCAL_SEQUENCE_COMPARISON_ONLY_NOT_FORMAL_LEAKAGE_ADJUDICATION',createdAt:new Date().toISOString(),repositoryRoot:root,inputs:files.map(p=>({path:p,bytes:read(p).length,sha256:hash(read(p))})),executionScript:{path:'/tmp/confovhh-gpr151-sequence/compare-nb6.mjs',sha256:hash(fs.readFileSync('/tmp/confovhh-gpr151-sequence/compare-nb6.mjs'))},scope:{localMetadataAndSequenceOnly:true,publicationsAccessed:false,nativeCoordinatesAccessed:false,structureImagesAccessed:false,labelsAccessed:false,entryDispositionAuthority:false,formalDevelopmentLeakageEdgeAuthority:false,knownParentLineageEstablished:false},methods:{numbering:'Existing pinned immunum 1.3.0 via numberVhhForLeakage, H chain IMGT, minimum confidence 0.5; raw residue map independently obtained from same pinned annotator.',spanConvention:'IMGT engine queryStart/queryEnd are zero-based inclusive; separately reported full-sequence spans and residue positions are one-based inclusive.',alignment:'Existing frozen global Needleman-Wunsch affine-gap BLOSUM62; gap open -10, extension -1; all alignment columns including gaps in identity denominator. Reported IMGT-position mismatches are explicit residue-mapping differences, not the traceback of that sequence alignment.',terminalResidues:'Prefix and suffix outside numbered domain are sequence facts; no construct or tag role inferred.'},candidates,candidatePair:comparison(candidates[0],candidates[1]),developmentReferences:development,developmentComparisons:comparisons,interpretation:['The two newly screened NB6 entities have exactly identical deposited full sequences.','6VI4 Nb6 is the closest local development reference under the recorded variable-domain alignment.','The candidate and 6VI4 have identical CDR1, CDR2 and CDR3 sequences, with three substitutions in the IMGT framework-2 region and different terminal residues outside the numbered domain.','This is a positive sequence-threshold review signal against an existing development reference, not by itself formal parentage, direct binding, construct clearance or entry exclusion.','Nb39-related local development references 5C1M and 6B73 are compared explicitly; no Nb39 identity is inferred from a nanobody name.']};
fs.writeFileSync('/tmp/confovhh-gpr151-sequence/nb6-local-comparison.json',JSON.stringify(output,null,2)+'\n');
console.log(JSON.stringify({comparisonFileSha256:hash(fs.readFileSync('/tmp/confovhh-gpr151-sequence/nb6-local-comparison.json')),allFrozenDevelopmentProfilesReproduced:profiles.length},null,2));
