export const RELEASE_VALIDATION = {
  schemaVersion: "1.5.0",
  softwareVersion: "0.5.0",
  engineLineage: {
    scientificCoreSourceMatchesAttestedV05: true,
    executedImmunumMatchesAttestedV05: true,
    dependencyEnvironmentMatchesAttestedV05: false,
    implementationSnapshot: "validation/v0.5-engine-implementation-snapshot-v1",
    statement: "The current product preserves the v0.5 scientific-core source and executed immunum 1.2.0 bytes, but uses a separately patched dependency/build environment. Byte-identical equivalence to the historical v0.5 lockfile is not claimed.",
  },
  runtime: {
    minimumNodeVersion: "22.18.0",
  },
  computationalBounds: {
    maximumAbsoluteSourceCoordinateAngstrom: 10_000_000,
    sasaMaximumCandidateDistanceChecks: 25_000_000,
    sasaMaximumOcclusionChecks: 250_000_000,
  },
  sasaPolicy: {
    singleAuditOrientation: "source-coordinate-frame",
    comparisonOrientation: "deterministic-proper-signed-frame",
    comparisonFrameAlgorithm: "selected-heavy-atom-farthest-signed-frame-v1",
  },
  mmcifParity: {
    structures: 17,
    exactMatches: 17,
  },
  depositedAssemblyOracles: {
    structures: 5,
    exactCountMatches: 5,
    maximumCoordinateErrorAngstrom: 0.0007702376719889841,
  },
  nativeInterfaceRegression: {
    structures: 17,
    interfacesDetected: 17,
    wholeComplexTranslationInvariances: 17,
    farTranslationControls: 102,
    farTranslationControlsRejected: 102,
  },
  realPredictionRunRegression: {
    status: "executed-public-producer-output-compatibility",
    outputArtifact: "validation/real-prediction-run-regression-v1.json",
    datasets: 2,
    sourceFiles: 26,
    coordinatePoses: 10,
    coordinatePosesAccepted: 10,
    paeAttachments: 10,
    paeAttachmentsAudited: 10,
    providers: ["alphafold-server", "colabfold"],
    domainValidation: false,
  },
  publicV05RegressionAttestation: {
    status: "executed-current-release-regression",
    outputArtifact: "validation/v0.5-public-regression-attestation-v1",
    sourceCommit: "5cb57617b54baa314513486885c402449f643406",
    runCompletedAt: "2026-08-27T19:57:15.069Z",
    implementationSha256: "7d98f49b97499c0cefb460c6b06673d2639c9aeef2adfdb2d1198e965766d5f7",
    executedImmunumSha256: "b0c5c0214fad3b74a09c5e73e257c421afe40854b61789eb894ad0ea8ae53d97",
    pdbMmcifSerializationPairs: 17,
    depositedAssemblyOracles: 5,
    nativeInterfaces: 17,
    wholeComplexTranslationChecks: 17,
    farTranslationControls: 102,
  },
  stateContextNativeRegression: {
    status: "public-native-context-coverage-inventory-only",
    nativeComplexes: 4,
    nativeInterfacesDetected: 4,
    receptorContextPairs: 2,
    sameVhhCrossContextPairs: 0,
  },
  dockqDevelopmentPilot: {
    status: "executed-development-only",
    targets: 5,
    generatedPoses: 360,
    retainedPoses: 360,
    controlsAndCrossChecks: 20,
    controlsAndCrossChecksPassed: 20,
    primaryPositiveRate: 0.636111111111,
    evidenceBand: {
      averagePrecision: 0.687853610626,
      averagePrecisionLift: 1.081281677441,
      auroc: 0.574180187644,
    },
    deltaSasa: {
      averagePrecision: 0.772742639817,
      averagePrecisionLift: 1.214965805109,
      auroc: 0.754144372319,
    },
  },
  dockqV05RegressionReplay: {
    status: "executed-post-label-regression-only",
    baselineArtifact: "validation/dockq-development-pilot-v1",
    outputArtifact: "validation/dockq-v0.5-regression-replay-v1",
    sourceCommit: "278ae1a74da133778fba5b17bc296a8e37f02e76",
    runCompletedAt: "2026-08-27T20:06:37.955Z",
    implementationSha256: "8926de3d4f9db9343a40659d8393d00db2f612572404c1b4bb8a7e41de3260d3",
    targets: 5,
    poses: 360,
    exactCoordinateMatches: 360,
    exactNonSasaAuditMatches: 360,
    sasaToleranceMatches: 360,
    exactFullAuditMatches: 21,
    deltaSasaToleranceAngstrom2: 1e-9,
    halfDeltaSasaToleranceAngstrom2: 5e-10,
    maximumDeltaSasaAbsoluteDifferenceAngstrom2: 1.0277290130034089e-10,
    maximumHalfDeltaSasaAbsoluteDifferenceAngstrom2: 5.1386450650170445e-11,
    exactDockqMatches: 360,
    exactCapriClassMatches: 360,
    controlsAndCrossChecks: 20,
    controlsAndCrossChecksPassed: 20,
    labelsPreviouslyObserved: true,
    independentValidation: false,
  },
  hardDecoySourceUniverse: {
    status: "archived-metadata-only-pending-scientific-dispositions",
    sourceSnapshot: "validation/hard-decoy-holdout-v3/source-snapshot-2026-08-29",
    entryMetadataSnapshot: "validation/hard-decoy-holdout-v3/entry-metadata-snapshot-2026-08-29",
    rcsbQueryUnionEntries: 2065,
    gpcrdbApiEntries: 1716,
    gpcrdbHtmlEntries: 1716,
    intersectionEntries: 287,
    sourceRawResponsesArchived: 12,
    sourceNormalizedCrossCheckPassed: true,
    entryMetadataCaptureCount: 2,
    entryMetadataRawResponsesArchived: 48,
    polymerEntities: 1401,
    reviewStrata: {
      directTargetCandidateReview: 39,
      auxiliaryOrConstructReview: 242,
      metadataResolutionRequired: 6,
    },
    pendingDispositionRows: 287,
    dispositionLedgerComplete: false,
    targetFreezePermitted: false,
    nativeCoordinatesAccessedDuringV3Preparation: false,
    dockqOrCapriLabelsAccessedDuringV3Preparation: false,
  },
  holdoutStatus: {
    currentProtocol: "HARD_DECOY_PROTOCOL_V3.md",
    selectedDesign: "sealed-one-way-native-epitope-boolean-oracle",
    v2CensusTerminal: true,
    holdoutDatasetExists: false,
    assembled: false,
    labeled: false,
    frozen: false,
    opened: false,
    evaluated: false,
    provisionalGroups: 7,
    formallyClearedGroups: 0,
    minimumRequiredGroups: 10,
    candidateDiscoveryComplete: false,
    epitopeBlindingDesignSelected: true,
    oracleImplementationValidated: false,
    oracleCustodyValidated: false,
    oracleRequestFrozen: false,
    oracleExecuted: false,
    leakageGraphFrozen: false,
    targetManifestFrozen: false,
    developmentEvaluationExecuted: false,
    statement: "The terminal hard-decoy v2 screen remains unchanged: seven groups are provisional, zero are formally cleared, and at least ten are required. Version 3 archives a repeat-fetched 287-entry historical four-term metadata sub-universe (not an exhaustive candidate universe) and selects a sealed one-way native-epitope oracle design, but all 287 scientific dispositions remain pending. Its request, independent implementation/container, custody and key ceremony, leakage graph, and target manifest are not frozen; the oracle was not executed. No holdout has been assembled, labeled, frozen, opened, or evaluated.",
  },
  claimFlags: {
    bindingValidated: false,
    affinityValidated: false,
    specificityValidated: false,
    functionalStateValidated: false,
    stateSelectivityValidated: false,
    sameVhhCrossContextValidated: false,
    membraneCompatibilityValidated: false,
    formalHoldoutEvaluated: false,
    hardDecoyProtocolCompleted: false,
    nearNativeRankingValidated: false,
    preliminaryNearNativeClaimAllowed: false,
  },
} as const;
