query ConfoVHHEntryMetadata($ids: [String!]!) {
  entries(entry_ids: $ids) {
    rcsb_id
    struct {
      title
    }
    struct_keywords {
      pdbx_keywords
      text
    }
    exptl {
      method
    }
    rcsb_accession_info {
      initial_release_date
    }
    rcsb_primary_citation {
      pdbx_database_id_DOI
      pdbx_database_id_PubMed
      title
    }
    rcsb_entry_info {
      experimental_method
      resolution_combined
      polymer_entity_count
    }
    polymer_entities {
      rcsb_id
      entity_poly {
        pdbx_seq_one_letter_code_can
        rcsb_entity_polymer_type
        type
      }
      rcsb_polymer_entity {
        pdbx_description
      }
      rcsb_polymer_entity_container_identifiers {
        entity_id
        asym_ids
        auth_asym_ids
        reference_sequence_identifiers {
          database_name
          database_accession
          provenance_source
        }
      }
      rcsb_entity_source_organism {
        ncbi_scientific_name
        ncbi_taxonomy_id
      }
    }
  }
}
